/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: eg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "eg.pb-c.h"
void   example__init
                     (Example         *message)
{
  static const Example init_value = EXAMPLE__INIT;
  *message = init_value;
}
size_t example__get_packed_size
                     (const Example *message)
{
  assert(message->base.descriptor == &example__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example__pack
                     (const Example *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example__pack_to_buffer
                     (const Example *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Example *
       example__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Example *)
     protobuf_c_message_unpack (&example__descriptor,
                                allocator, len, data);
}
void   example__free_unpacked
                     (Example *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor example__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Example, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Example, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Example, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange example__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor example__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Example",
  "Example",
  "Example",
  "",
  sizeof(Example),
  3,
  example__field_descriptors,
  example__field_indices_by_name,
  1,  example__number_ranges,
  (ProtobufCMessageInit) example__init,
  NULL,NULL,NULL    /* reserved[123] */
};
