/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: eg.proto */

#ifndef PROTOBUF_C_eg_2eproto__INCLUDED
#define PROTOBUF_C_eg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Example Example;


/* --- enums --- */


/* --- messages --- */

struct  Example
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  float value;
};
#define EXAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&example__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0 }


/* Example methods */
void   example__init
                     (Example         *message);
size_t example__get_packed_size
                     (const Example   *message);
size_t example__pack
                     (const Example   *message,
                      uint8_t             *out);
size_t example__pack_to_buffer
                     (const Example   *message,
                      ProtobufCBuffer     *buffer);
Example *
       example__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   example__free_unpacked
                     (Example *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Example_Closure)
                 (const Example *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor example__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_eg_2eproto__INCLUDED */
