/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: register.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "register.pb-c.h"
void   register_request__init
                     (RegisterRequest         *message)
{
  static const RegisterRequest init_value = REGISTER_REQUEST__INIT;
  *message = init_value;
}
size_t register_request__get_packed_size
                     (const RegisterRequest *message)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t register_request__pack
                     (const RegisterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t register_request__pack_to_buffer
                     (const RegisterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &register_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RegisterRequest *
       register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RegisterRequest *)
     protobuf_c_message_unpack (&register_request__descriptor,
                                allocator, len, data);
}
void   register_request__free_unpacked
                     (RegisterRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &register_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   answer_request__init
                     (AnswerRequest         *message)
{
  static const AnswerRequest init_value = ANSWER_REQUEST__INIT;
  *message = init_value;
}
size_t answer_request__get_packed_size
                     (const AnswerRequest *message)
{
  assert(message->base.descriptor == &answer_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t answer_request__pack
                     (const AnswerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &answer_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t answer_request__pack_to_buffer
                     (const AnswerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &answer_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AnswerRequest *
       answer_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AnswerRequest *)
     protobuf_c_message_unpack (&answer_request__descriptor,
                                allocator, len, data);
}
void   answer_request__free_unpacked
                     (AnswerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &answer_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor register_request__field_descriptors[1] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegisterRequest, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned register_request__field_indices_by_name[] = {
  0,   /* field[0] = username */
};
static const ProtobufCIntRange register_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor register_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RegisterRequest",
  "RegisterRequest",
  "RegisterRequest",
  "",
  sizeof(RegisterRequest),
  1,
  register_request__field_descriptors,
  register_request__field_indices_by_name,
  1,  register_request__number_ranges,
  (ProtobufCMessageInit) register_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor answer_request__field_descriptors[2] =
{
  {
    "qu_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AnswerRequest, qu_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "answer_idx",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AnswerRequest, answer_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned answer_request__field_indices_by_name[] = {
  1,   /* field[1] = answer_idx */
  0,   /* field[0] = qu_id */
};
static const ProtobufCIntRange answer_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor answer_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AnswerRequest",
  "AnswerRequest",
  "AnswerRequest",
  "",
  sizeof(AnswerRequest),
  2,
  answer_request__field_descriptors,
  answer_request__field_indices_by_name,
  1,  answer_request__number_ranges,
  (ProtobufCMessageInit) answer_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
